# Generated by Django 3.0 on 2020-09-18 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=' ', max_length=50)),
                ('manufacturer', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(default=' ', max_length=50)),
                ('date_of_purchase', models.CharField(default=' ', max_length=50)),
                ('last_serviced', models.CharField(default=' ', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='clients.Client')),
            ],
        ),
    ]
